from test import *


all = [
    Test("wilbertpol/gpu/hblank_ly_scx_timing_nops.gb", runtime=1.5),
    Test("wilbertpol/gpu/hblank_ly_scx_timing_variant_nops.gb", runtime=1.5),
    Test("wilbertpol/gpu/hblank_ly_scx_timing-C.gb", runtime=1.5, model=CGB),
    Test("wilbertpol/gpu/hblank_ly_scx_timing-GS.gb", runtime=1.5),
    Test("wilbertpol/gpu/intr_0_timing.gb", runtime=1.5),
    Test("wilbertpol/gpu/intr_1_timing.gb", runtime=1.5),
    Test("wilbertpol/gpu/intr_2_0_timing.gb", runtime=1.5),
    Test("wilbertpol/gpu/intr_2_mode0_scx1_timing_nops.gb", runtime=1.5),
    Test("wilbertpol/gpu/intr_2_mode0_scx2_timing_nops.gb", runtime=1.5),
    Test("wilbertpol/gpu/intr_2_mode0_scx3_timing_nops.gb", runtime=1.5),
    Test("wilbertpol/gpu/intr_2_mode0_scx4_timing_nops.gb", runtime=1.5),
    Test("wilbertpol/gpu/intr_2_mode0_scx5_timing_nops.gb", runtime=1.5),
    Test("wilbertpol/gpu/intr_2_mode0_scx6_timing_nops.gb", runtime=1.5),
    Test("wilbertpol/gpu/intr_2_mode0_scx7_timing_nops.gb", runtime=1.5),
    Test("wilbertpol/gpu/intr_2_mode0_scx8_timing_nops.gb", runtime=1.5),
    Test("wilbertpol/gpu/intr_2_mode0_timing_sprites_nops.gb", runtime=1.5),
    Test("wilbertpol/gpu/intr_2_mode0_timing_sprites_scx1_nops.gb", runtime=1.5),
    Test("wilbertpol/gpu/intr_2_mode0_timing_sprites_scx2_nops.gb", runtime=1.5),
    Test("wilbertpol/gpu/intr_2_mode0_timing_sprites_scx3_nops.gb", runtime=1.5),
    Test("wilbertpol/gpu/intr_2_mode0_timing_sprites_scx4_nops.gb", runtime=1.5),
    Test("wilbertpol/gpu/intr_2_timing.gb", runtime=1.5),
    Test("wilbertpol/gpu/lcdon_mode_timing.gb", runtime=1.5),
    # Test("wilbertpol/gpu/ly_lyc_0_write-C.gb", runtime=1.5, model=CGB),
    Test("wilbertpol/gpu/ly_lyc_0_write-GS.gb", runtime=1.5),
    # Test("wilbertpol/gpu/ly_lyc_0-C.gb", runtime=1.5, model=CGB),
    Test("wilbertpol/gpu/ly_lyc_0-GS.gb", runtime=1.5),
    # Test("wilbertpol/gpu/ly_lyc_144-C.gb", runtime=1.5, model=CGB),
    Test("wilbertpol/gpu/ly_lyc_144-GS.gb", runtime=1.5),
    # Test("wilbertpol/gpu/ly_lyc_153_write-C.gb", runtime=1.5, model=CGB),
    Test("wilbertpol/gpu/ly_lyc_153_write-GS.gb", runtime=1.5),
    # Test("wilbertpol/gpu/ly_lyc_153-C.gb", runtime=1.5, model=CGB),
    Test("wilbertpol/gpu/ly_lyc_153-GS.gb", runtime=1.5),
    # Test("wilbertpol/gpu/ly_lyc_write-C.gb", runtime=1.5, model=CGB),
    Test("wilbertpol/gpu/ly_lyc_write-GS.gb", runtime=1.5),
    # Test("wilbertpol/gpu/ly_lyc-C.gb", runtime=1.5, model=CGB),
    Test("wilbertpol/gpu/ly_lyc-GS.gb", runtime=1.5),
    # Test("wilbertpol/gpu/ly_new_frame-C.gb", runtime=1.5, model=CGB),
    Test("wilbertpol/gpu/ly_new_frame-GS.gb", runtime=1.5),
    Test("wilbertpol/gpu/ly00_01_mode0_2.gb", runtime=1.5),
    Test("wilbertpol/gpu/ly00_mode0_2-GS.gb", runtime=1.5),
    Test("wilbertpol/gpu/ly00_mode1_0-GS.gb", runtime=1.5),
    # Test("wilbertpol/gpu/ly00_mode1_2-C.gb", runtime=1.5, model=CGB),
    Test("wilbertpol/gpu/ly00_mode2_3.gb", runtime=1.5),
    Test("wilbertpol/gpu/ly00_mode3_0.gb", runtime=1.5),
    Test("wilbertpol/gpu/ly143_144_145.gb", runtime=1.5),
    Test("wilbertpol/gpu/ly143_144_152_153.gb", runtime=1.5),
    Test("wilbertpol/gpu/ly143_144_mode0_1.gb", runtime=1.5),
    Test("wilbertpol/gpu/ly143_144_mode3_0.gb", runtime=1.5),
    Test("wilbertpol/gpu/stat_write_if-C.gb", runtime=1.5, model=CGB),
    Test("wilbertpol/gpu/stat_write_if-GS.gb", runtime=1.5),
    Test("wilbertpol/gpu/vblank_if_timing.gb", runtime=1.5),
]
